name: Create Azure VM

on:
  push:
    branches:
      - main

jobs:
  create-vm:
    runs-on: ubuntu-latest
    env:
      RESOURCE_GROUP: frst-env
      NAME: seeqgold-vm
      ADMIN_USERNAME: seeqgold
      ADMIN_PASSWORD: omolaja2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set up Azure CLI
        uses: azure/CLI@v1
        with:
          azcliversion: 2.32.0
           inlineScript:az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }}

      - name: Login to Azure
        run: az login --service-principal -u ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create Azure VM
        run: |
          az vm create \
            --resource-group $RESOURCE_GROUP \
            --name $NAME \
            --image UbuntuLTS \
            --admin-username $ADMIN_USERNAME \
            --admin-password $ADMIN_PASSWORD \
            --size Standard_DS1_v2
      - name: Debug Directory
        run: |
            ls -la
            ls -la /home/runner/work/_temp

